Repository ManageIQ/floe, pull requests merged in 2023-12, with the labels that each got.

#144 Remove more core dependency from ReferencePath
  CHANGELOG.md
  floe.gemspec
  lib/floe/workflow/reference_path.rb
  spec/workflow/reference_path_spec.rb
Labels: refactoring

#145 Allow a State to set a value in Credentials for subsequent states
  CHANGELOG.md
  README.md
  examples/set-credential.asl
  lib/floe.rb
  lib/floe/workflow/path.rb
  lib/floe/workflow/states/input_output_mixin.rb
  lib/floe/workflow/states/pass.rb
  lib/floe/workflow/states/task.rb
  spec/workflow/states/pass_spec.rb
  spec/workflow/states/task_spec.rb
Labels: enhancement

#149 Run multiple workflows in exe/floe
  exe/floe
  lib/floe/workflow.rb
  lib/floe/workflow/context.rb
  lib/floe/workflow/state.rb
  spec/workflow/states/fail_spec.rb
  spec/workflow_spec.rb
Labels: enhancement

#150 Support podman with empty output
  lib/floe/workflow/states/task.rb
Labels: bug

#151 Add secure options for passing credentials via command-line
  README.md
  exe/floe
Labels: enhancement
