Repository ManageIQ/floe, pull requests merged in 2023-08, with the labels that each got.

#80 move end out of the root state node
  lib/floe/workflow/state.rb
  lib/floe/workflow/states/choice.rb
  lib/floe/workflow/states/fail.rb
  lib/floe/workflow/states/pass.rb
  lib/floe/workflow/states/succeed.rb
  lib/floe/workflow/states/task.rb
  lib/floe/workflow/states/wait.rb
  spec/workflow/states/choice_spec.rb
  spec/workflow/states/fail_spec.rb
  spec/workflow/states/pass_spec.rb
  spec/workflow/states/succeed_spec.rb
  spec/workflow/states/task_spec.rb
  spec/workflow/states/wait_spec.rb
Labels: refactoring

#81 Add --network=host option to Docker/Podman
  README.md
  lib/floe/workflow/runner/docker.rb
  lib/floe/workflow/runner/podman.rb
  spec/workflow/runner/docker_spec.rb
  spec/workflow/runner/podman_spec.rb
Labels: enhancement

#71 Parse completed expressions rather than parse at runtime
  lib/floe.rb
  lib/floe/workflow/choice_rule.rb
  lib/floe/workflow/choice_rule/and.rb
  lib/floe/workflow/choice_rule/boolean.rb
  lib/floe/workflow/choice_rule/not.rb
  lib/floe/workflow/choice_rule/or.rb
  spec/workflow/choice_rule_spec.rb
Labels: enhancement

#88 Fix State Duration units
  lib/floe/workflow.rb
Labels: bug

#83 Parse payload template at initialize not runtime
  lib/floe/workflow/payload_template.rb
  spec/workflow/payload_template_spec.rb
Labels: enhancement

#89 fix complexity of parse_payload_hash
  lib/floe/workflow/payload_template.rb
Labels: refactoring

#90 Add global podman runner options
  CHANGELOG.md
  README.md
  lib/floe/workflow/runner/podman.rb
  spec/workflow/runner/podman_spec.rb
Labels: enhancement
