Repository ManageIQ/floe, pull requests merged in 2023-09, with the labels that each got.

#85 Move state from workflow into context
  lib/floe/workflow.rb
  lib/floe/workflow/context.rb
  lib/floe/workflow/states/choice.rb
  lib/floe/workflow/states/fail.rb
  lib/floe/workflow/states/pass.rb
  lib/floe/workflow/states/succeed.rb
  lib/floe/workflow/states/task.rb
  lib/floe/workflow/states/wait.rb
  spec/workflow/context_spec.rb
  spec/workflow/states/choice_spec.rb
  spec/workflow/states/fail_spec.rb
  spec/workflow/states/pass_spec.rb
  spec/workflow/states/succeed_spec.rb
  spec/workflow/states/task_spec.rb
  spec/workflow/states/wait_spec.rb
  spec/workflow_spec.rb
Labels: enhancement

#52 Add ability to run workflows asynchronously
  lib/floe/workflow/runner.rb
  lib/floe/workflow/runner/docker.rb
  lib/floe/workflow/runner/kubernetes.rb
  lib/floe/workflow/runner/podman.rb
  lib/floe/workflow/states/task.rb
  spec/workflow/runner/docker_spec.rb
  spec/workflow/runner/kubernetes_spec.rb
  spec/workflow/runner/podman_spec.rb
  spec/workflow/states/task_spec.rb
Labels: enhancement

#92 Add a nonblocking workflow step function
  CHANGELOG.md
  README.md
  exe/floe
  lib/floe/workflow.rb
  lib/floe/workflow/context.rb
  lib/floe/workflow/state.rb
  lib/floe/workflow/states/choice.rb
  lib/floe/workflow/states/fail.rb
  lib/floe/workflow/states/pass.rb
  lib/floe/workflow/states/succeed.rb
  lib/floe/workflow/states/task.rb
  lib/floe/workflow/states/wait.rb
  spec/workflow/states/task_spec.rb
  spec/workflow/states/wait_spec.rb
  spec/workflow_spec.rb
Labels: enhancement

#99 RunnerContext should use string keys
  lib/floe/workflow.rb
  lib/floe/workflow/runner/docker.rb
  lib/floe/workflow/runner/kubernetes.rb
  lib/floe/workflow/runner/podman.rb
  lib/floe/workflow/state.rb
  lib/floe/workflow/states/wait.rb
  spec/workflow/runner/docker_spec.rb
  spec/workflow/runner/kubernetes_spec.rb
  spec/workflow/runner/podman_spec.rb
  spec/workflow/states/task_spec.rb
  spec/workflow/states/wait_spec.rb
  spec/workflow_spec.rb
Labels: bug

#98 [test] specs for Workflow#step(_nonblock)
  spec/workflow_spec.rb
Labels: test

#97 Move workflow#step into State#run
  lib/floe/workflow.rb
  lib/floe/workflow/state.rb
  lib/floe/workflow/states/choice.rb
  lib/floe/workflow/states/fail.rb
  lib/floe/workflow/states/pass.rb
  lib/floe/workflow/states/succeed.rb
  lib/floe/workflow/states/task.rb
  lib/floe/workflow/states/wait.rb
  spec/workflow/states/task_spec.rb
Labels: enhancement

#102 only provide output once workflow is complete
  lib/floe/workflow.rb
  spec/workflow_spec.rb
Labels: bug

#101 Cops
  Gemfile
  exe/floe
  floe.gemspec
  lib/floe/null_logger.rb
  lib/floe/workflow/choice_rule/data.rb
  lib/floe/workflow/runner/kubernetes.rb
  lib/floe/workflow/states/map.rb
  lib/floe/workflow/states/parallel.rb
Labels: technical debt

#104 Combine stdout and stderr for podman/docker
  lib/floe/workflow/runner/docker.rb
  lib/floe/workflow/runner/podman.rb
  spec/workflow/runner/docker_spec.rb
  spec/workflow/runner/podman_spec.rb
Labels: bug

#107 [test] test Runner#run_async! and not Runner#run!
  spec/workflow/runner/docker_spec.rb
  spec/workflow/runner/kubernetes_spec.rb
  spec/workflow/runner/podman_spec.rb
Labels: test
