Repository ManageIQ/floe, pull requests merged in 2023-10, with the labels that each got.

#110 Task#Catcherr puts an "Error" into the output
  lib/floe/workflow/catcher.rb
  lib/floe/workflow/states/task.rb
Labels: bug

#108 Add Fail#CausePath and Fail#ErrorPath
  lib/floe/workflow/state.rb
  lib/floe/workflow/states/fail.rb
  spec/workflow/states/fail_spec.rb
  spec/workflow_spec.rb
Labels: bug

#116 drop active_support from specs
  spec/workflow_spec.rb
Labels: bug, test

#112 Fix task output handling by adding an output marker
  lib/floe/workflow/runner.rb
  lib/floe/workflow/states/task.rb
  spec/workflow/states/task_spec.rb
Labels: bug

#100 Add Task#Retrier incremental backoff and Wait#Timestamp
  Gemfile
  lib/floe/workflow/state.rb
  lib/floe/workflow/states/task.rb
  lib/floe/workflow/states/wait.rb
  spec/spec_helper.rb
  spec/workflow/states/task_spec.rb
  spec/workflow/states/wait_spec.rb
  spec/workflow_spec.rb
Labels: enhancement

#121 Test task
  spec/workflow/states/task_spec.rb
Labels: test

#119 Fix Runner interface
  lib/floe/workflow/runner.rb
Labels: bug, technical debt

#118 drop value_or_path
  lib/floe/workflow/state.rb
  lib/floe/workflow/states/fail.rb
  lib/floe/workflow/states/wait.rb
Labels: technical debt

#124 Don't put credentials into input
  lib/floe/workflow/runner/docker.rb
  lib/floe/workflow/runner/podman.rb
Labels: bug

#128 for task errors, use the json on the last line
  lib/floe/workflow/states/task.rb
  spec/workflow/states/task_spec.rb
Labels: bug

#129 exe/floe return success status if the workflow was successful
  exe/floe
Labels: enhancement

#126 remove newline at the end of runner output
  lib/floe/workflow/states/task.rb
Labels: bug

#113 [test] Drop calls to blocking run/step
  spec/workflow/states/choice_spec.rb
  spec/workflow/states/pass_spec.rb
  spec/workflow/states/succeed_spec.rb
  spec/workflow_spec.rb
Labels: test

#109 Drop Runner#run!
  lib/floe/workflow/runner/docker.rb
  lib/floe/workflow/runner/kubernetes.rb
  lib/floe/workflow/runner/podman.rb
Labels: technical debt

#131 Add ability to pass workflow service account to kube runner
  examples/workflow.asl
  lib/floe/workflow/runner/kubernetes.rb
  spec/workflow/runner/kubernetes_spec.rb
Labels: enhancement

#132 Prefix pod names with 'floe-'
  lib/floe.rb
  lib/floe/workflow/runner/docker.rb
  lib/floe/workflow/runner/docker_mixin.rb
  lib/floe/workflow/runner/kubernetes.rb
  lib/floe/workflow/runner/podman.rb
  spec/workflow/runner/docker_spec.rb
  spec/workflow/runner/kubernetes_spec.rb
  spec/workflow/runner/podman_spec.rb
Labels: enhancement

#134 Fix issue where certain docker image names cannot be pod names
  lib/floe/workflow/runner/docker_mixin.rb
  lib/floe/workflow/runner/kubernetes.rb
  spec/workflow/runner/kubernetes_spec.rb
Labels: bug

#137 Fix uninitialized constant RSpec::Support::Differ
  spec/workflow/runner/docker_spec.rb
Labels: bug, test
