Repository ManageIQ/floe, pull requests merged in 2023-11, with the labels that each got.

#123 [test] Each task defines own input and output
  spec/workflow/states/task_spec.rb
Labels: test

#138 Fix a new task_spec test after task_spec_helper merge
  spec/workflow/states/task_spec.rb
Labels: bug, test

#136 Validate that the workflow payload is correct
  lib/floe.rb
  lib/floe/workflow.rb
  lib/floe/workflow/path.rb
  lib/floe/workflow/state.rb
  lib/floe/workflow/states/choice.rb
  lib/floe/workflow/states/non_terminal_mixin.rb
  lib/floe/workflow/states/pass.rb
  lib/floe/workflow/states/task.rb
  lib/floe/workflow/states/wait.rb
  spec/workflow/path_spec.rb
  spec/workflow/states/choice_spec.rb
  spec/workflow/states/task_spec.rb
  spec/workflow/states/wait_spec.rb
  spec/workflow_spec.rb
Labels: enhancement

#135 Handle ImagePullErr/ImagePullBackOff as errors
  lib/floe/workflow/runner/kubernetes.rb
  lib/floe/workflow/states/task.rb
  spec/workflow/runner/kubernetes_spec.rb
Labels: bug

#140 Refactor the Podman runner to be a Docker subclass
  lib/floe/workflow/runner/docker.rb
  lib/floe/workflow/runner/podman.rb
Labels: refactoring

#142 Extract run_container_params for docker/podman
  lib/floe/workflow/runner/docker.rb
  lib/floe/workflow/runner/podman.rb
Labels: refactoring
