Repository ManageIQ/floe, pull requests merged in 2023-03, with the labels that each got.

#38 Add Ruby 3.2 to CI. Update checkout action version.
  .github/workflows/ci.yaml
Labels: enhancement

#41 Fix readme reference to workflow file [skip ci]
  README.md
Labels: documentation

#43 Fix repository name in CHANGELOG.md
  CHANGELOG.md
Labels: bug
