Repository ManageIQ/floe, pull requests merged in 2023-07, with the labels that each got.

#53 Use kubeclient gem instead of kubectl
  CHANGELOG.md
  README.md
  floe.gemspec
  lib/floe/workflow/runner/kubernetes.rb
  spec/workflow/runner/kubernetes_spec.rb
Labels: enhancement

#54 Remove to_dot/to_svg code
  .github/workflows/ci.yaml
  lib/floe/workflow.rb
  lib/floe/workflow/state.rb
  lib/floe/workflow/states/choice.rb
  lib/floe/workflow/states/fail.rb
  lib/floe/workflow/states/succeed.rb
  spec/workflow/states/choice_spec.rb
  spec/workflow/states/fail_spec.rb
  spec/workflow/states/pass_spec.rb
  spec/workflow/states/succeed_spec.rb
  spec/workflow/states/task_spec.rb
  spec/workflow/states/wait_spec.rb
  spec/workflow_spec.rb
Labels: technical debt

#55 Change default rake task to spec
  .github/workflows/ci.yaml
  Rakefile
Labels: test

#56 Fix missing changelog diff links
  CHANGELOG.md
Labels: documentation

#59 CLOCK_MONOTONIC cannot be used to get wall time
  CHANGELOG.md
  lib/floe/workflow.rb
Labels: bug

#57 Set workflow output on completion
  CHANGELOG.md
  exe/floe
  lib/floe/workflow.rb
Labels: enhancement

#58 Use the context accessor methods
  lib/floe/workflow.rb
  lib/floe/workflow/context.rb
Labels: enhancement

#60 Fix EnteredTime/FinishedTime not in UTC
  lib/floe/workflow.rb
Labels: bug

#62 Minor tweak to `Fail#end?`
  lib/floe/workflow/states/fail.rb
Labels: refactoring

#65 Remove `Success#end?` method override
  lib/floe/workflow/states/succeed.rb
Labels: refactoring

#68 Refactor input output path handling
  lib/floe/workflow.rb
  lib/floe/workflow/state.rb
  lib/floe/workflow/states/choice.rb
  lib/floe/workflow/states/fail.rb
  lib/floe/workflow/states/pass.rb
  lib/floe/workflow/states/succeed.rb
  lib/floe/workflow/states/task.rb
  lib/floe/workflow/states/wait.rb
  spec/workflow/states/task_spec.rb
Labels: refactoring

#69 Fix double json.parse and context default value
  lib/floe/workflow.rb
Labels: bug

#73 don't pick up real KUBECONFIG for tests
  spec/workflow/runner/kubernetes_spec.rb
Labels: bug, test

#75 Link PRs in changelog
  CHANGELOG.md
Labels: documentation

#76 Fix storing next_state in Context
  lib/floe/workflow.rb
Labels: bug
