Repository ManageIQ/floe, pull requests merged in 2024-09, with the labels that each got.

#276 Choice State enforces type checking
  lib/floe/workflow/choice_rule/data.rb
  spec/workflow/choice_rule_spec.rb
Labels: enhancement

#277 For Choice validation, use instance variables and not payload
  lib/floe/workflow/states/choice.rb
Labels: refactoring

#279 Add WorkflowBase base class for Workflow
  lib/floe.rb
  lib/floe/workflow.rb
  lib/floe/workflow_base.rb
Labels: refactoring

#244 Add tool for using the aws stepfunctions simulator
  tools/step_functions
Labels: enhancement, tools

#251 Add shared example to cut down on Wait spec duplication
  spec/workflow/states/wait_spec.rb
Labels: test

#280 Fix case on log messages
  lib/floe/workflow.rb
  spec/cli_spec.rb
Labels: cleanup

#281 Drop sig until we choose to use it
  sig/floe.rbs/floe.rbs
Labels: technical debt
