Repository ManageIQ/floe, pull requests merged in 2024-10, with the labels that each got.

#184 Implement Map state
  examples/map.asl
  lib/floe.rb
  lib/floe/workflow.rb
  lib/floe/workflow/item_processor.rb
  lib/floe/workflow/states/map.rb
  lib/floe/workflow_base.rb
  spec/workflow/item_processor_spec.rb
  spec/workflow/states/map_spec.rb
Labels: enhancement

#282 Map state add tolerated failure
  lib/floe.rb
  lib/floe/workflow/states/map.rb
  lib/floe/workflow/states/retry_catch_mixin.rb
  lib/floe/workflow/states/task.rb
  spec/workflow/states/map_spec.rb
Labels: enhancement

#286 Minor rubocop fixes in step_functions
  spec/workflow/states/map_spec.rb
  tools/step_functions
Labels: technical debt

#284 Handle either tolerated_failure_count or tolerated_failure_percentage
  lib/floe/workflow/states/map.rb
  spec/workflow/states/map_spec.rb
Labels: enhancement

#285 Return ExceedToleratedFailureThreshold if ToleratedFailureCount/Percentage is present
  lib/floe/workflow/states/map.rb
  spec/workflow/states/map_spec.rb
Labels: enhancement

#289 Extract methods cli
  lib/floe/cli.rb
Labels: refactoring

#283 Run Map iterations in parallel up to MaxConcurrency
  examples/map.asl
  lib/floe/workflow/states/map.rb
  spec/workflow/states/map_spec.rb
Labels: enhancement

#291 Parallel state
  examples/parallel.asl
  lib/floe.rb
  lib/floe/workflow/branch.rb
  lib/floe/workflow/states/child_workflow_mixin.rb
  lib/floe/workflow/states/map.rb
  lib/floe/workflow/states/parallel.rb
  spec/shared/workflow_base.rb
  spec/spec_helper.rb
  spec/workflow/branch_spec.rb
  spec/workflow/item_processor_spec.rb
  spec/workflow/states/parallel_spec.rb
Labels: enhancement

#292 Document features not yet supported
  README.md
Labels: documentation

#223 Separate workflow/context with different loggers
  lib/floe/cli.rb
  lib/floe/container_runner/docker.rb
  lib/floe/container_runner/kubernetes.rb
  lib/floe/logging.rb
  lib/floe/runner.rb
  lib/floe/workflow.rb
  lib/floe/workflow/context.rb
  lib/floe/workflow/state.rb
  lib/floe/workflow/states/retry_catch_mixin.rb
  spec/cli_spec.rb
Labels: enhancement
