Repository ManageIQ/floe, pull requests merged in 2024-07, with the labels that each got.

#234 Set Floe.logger.level if DEBUG env var set
  lib/floe/cli.rb
Labels: developer

#194 InstrinsicFunction foundation + States.Array, States.UUID
  floe.gemspec
  lib/floe.rb
  lib/floe/workflow/intrinsic_function.rb
  lib/floe/workflow/intrinsic_function/parser.rb
  lib/floe/workflow/intrinsic_function/transformer.rb
  spec/workflow/intrinsic_function/parser_spec.rb
  spec/workflow/intrinsic_function_spec.rb
Labels: enhancement

#237 Fix edge cases with States.Array
  lib/floe/workflow/intrinsic_function/parser.rb
  lib/floe/workflow/intrinsic_function/transformer.rb
  spec/workflow/intrinsic_function/parser_spec.rb
  spec/workflow/intrinsic_function_spec.rb
Labels: bug

#229 Pass full path name to State.new for better errors
  lib/floe.rb
  lib/floe/validation_mixin.rb
  lib/floe/workflow.rb
  lib/floe/workflow/catcher.rb
  lib/floe/workflow/choice_rule.rb
  lib/floe/workflow/retrier.rb
  lib/floe/workflow/state.rb
  lib/floe/workflow/states/choice.rb
  lib/floe/workflow/states/non_terminal_mixin.rb
  lib/floe/workflow/states/task.rb
  spec/workflow/choice_rule_spec.rb
  spec/workflow/error_matcher_mixin_spec.rb
  spec/workflow/state_spec.rb
  spec/workflow/states/choice_spec.rb
  spec/workflow/states/pass_spec.rb
  spec/workflow/states/task_spec.rb
  spec/workflow_spec.rb
Labels: enhancement

#242 Add intrinsic functions
  lib/floe/workflow/intrinsic_function/parser.rb
  lib/floe/workflow/intrinsic_function/transformer.rb
  spec/workflow/intrinsic_function/parser_spec.rb
  spec/workflow/intrinsic_function_spec.rb
Labels: enhancement

#227 Validate that state machine input is valid JSON
  lib/floe.rb
  lib/floe/cli.rb
  lib/floe/workflow.rb
  lib/floe/workflow/context.rb
  spec/workflow/context_spec.rb
  spec/workflow/error_matcher_mixin_spec.rb
  spec/workflow/retrier_spec.rb
  spec/workflow/state_spec.rb
  spec/workflow/states/choice_spec.rb
  spec/workflow/states/fail_spec.rb
  spec/workflow/states/pass_spec.rb
  spec/workflow/states/succeed_spec.rb
  spec/workflow/states/task_spec.rb
  spec/workflow/states/wait_spec.rb
  spec/workflow_spec.rb
Labels: enhancement

#245 Move the Parslet parse into initialize so that invalid function definition will fail on workflow load
  lib/floe/workflow/intrinsic_function.rb
  spec/workflow/intrinsic_function_spec.rb
Labels: enhancement

#249 State#cause_path, error_path
  lib/floe/workflow/states/fail.rb
Labels: developer

#247 Wait should delay from now and not from when the method started
  lib/floe/workflow/state.rb
Labels: bug

#250 Validate Catcher Next
  lib/floe/workflow/catcher.rb
  spec/workflow/states/task_spec.rb
  spec/workflow_spec.rb
Labels: enhancement

#248 Add spec/supports
  spec/spec_helper.rb
  spec/support/common_methods.rb
  spec/workflow_spec.rb
Labels: test

#252 Fix invalid container names after normalizing
  lib/floe/container_runner/docker_mixin.rb
  spec/container_runner/kubernetes_spec.rb
Labels: bug
