Repository ManageIQ/floe, pull requests merged in 2024-04, with the labels that each got.

#165 Output contains output and errors
  lib/floe/workflow/state.rb
  lib/floe/workflow/states/choice.rb
  lib/floe/workflow/states/fail.rb
  lib/floe/workflow/states/pass.rb
  lib/floe/workflow/states/succeed.rb
  lib/floe/workflow/states/task.rb
  lib/floe/workflow/states/wait.rb
Labels: enhancement

#170 add Workflow#comment
  lib/floe/workflow.rb
  spec/workflow_spec.rb
Labels: enhancement

#169 Add support for pluggable schemes
  exe/floe
  lib/floe.rb
  lib/floe/runner/container_runner.rb
  lib/floe/runner/container_runner/docker.rb
  lib/floe/runner/container_runner/docker_mixin.rb
  lib/floe/runner/container_runner/kubernetes.rb
  lib/floe/runner/container_runner/podman.rb
  lib/floe/workflow/runner.rb
  spec/runner/docker_spec.rb
  spec/runner/kubernetes_spec.rb
  spec/runner/podman_spec.rb
  spec/spec_helper.rb
Labels: enhancement

#171 Collapse some namespaces
  exe/floe
  lib/floe.rb
  lib/floe/container_runner.rb
  lib/floe/container_runner/docker.rb
  lib/floe/container_runner/docker_mixin.rb
  lib/floe/container_runner/kubernetes.rb
  lib/floe/container_runner/podman.rb
  lib/floe/runner.rb
  lib/floe/runner/container_runner.rb
  lib/floe/runner/container_runner/docker.rb
  lib/floe/runner/container_runner/docker_mixin.rb
  lib/floe/runner/container_runner/kubernetes.rb
  lib/floe/runner/container_runner/podman.rb
  lib/floe/workflow/runner.rb
  lib/floe/workflow/states/task.rb
  spec/container_runner/docker_spec.rb
  spec/container_runner/kubernetes_spec.rb
  spec/container_runner/podman_spec.rb
  spec/spec_helper.rb
  spec/workflow/states/task_spec.rb
Labels: refactoring

#172 Add basic spec around exe/floe
  spec/exe/floe_spec.rb
Labels: test

#173 Ensure the local code is loaded in exe/floe
  exe/floe
Labels: bug

#174 Fix issues with exe/floe and various combinations of workflow and input
  exe/floe
  lib/floe/workflow/context.rb
  spec/exe/data/workflow.asl
  spec/exe/floe_spec.rb
Labels: bug

#176 drop run!
  lib/floe/runner.rb
Labels: enhancement
