Repository ManageIQ/floe, pull requests merged in 2024-01, with the labels that each got.

#155 Add a Docker Runner pull-policy option
  CHANGELOG.md
  README.md
  lib/floe/workflow/runner/docker.rb
  lib/floe/workflow/runner/kubernetes.rb
  lib/floe/workflow/runner/podman.rb
  spec/workflow/runner/docker_spec.rb
  spec/workflow/runner/kubernetes_spec.rb
  spec/workflow/runner/podman_spec.rb
Labels: enhancement

#154 Fix run_container logger saying docker when using podman
  lib/floe/workflow/runner/docker.rb
Labels: bug

#147 extra cli options
  exe/floe
Labels: enhancement

#156 Ensure that wf.credentials is not-nil
  lib/floe/workflow.rb
  spec/workflow_spec.rb
Labels: bug

#157 Default to waiting infinitely
  lib/floe/workflow.rb
  lib/floe/workflow/state.rb
Labels: enhancement

#152 Create docker runners factory and add scheme
  exe/floe
  lib/floe.rb
  lib/floe/workflow/runner.rb
Labels: refactoring
