Repository ManageIQ/floe, pull requests merged in 2024-06, with the labels that each got.

#199 ResultPath=$ replaces complete output
  lib/floe/workflow/reference_path.rb
  spec/workflow/reference_path_spec.rb
  spec/workflow/states/task_spec.rb
Labels: bug

#200 Fix retrier backoff values
  lib/floe/workflow/retrier.rb
  spec/workflow/retrier_spec.rb
  spec/workflow/states/task_spec.rb
Labels: bug

#205 Update gemspec summary
  floe.gemspec
Labels: developer

#204 Simpler State#long_name
  lib/floe/workflow/state.rb
Labels: refactoring

#206 State only modifies Context#state - prep for Map/Parallel
  README.md
  lib/floe/workflow.rb
  lib/floe/workflow/context.rb
  lib/floe/workflow/state.rb
  spec/workflow/state_spec.rb
  spec/workflow/states/choice_spec.rb
  spec/workflow/states/fail_spec.rb
  spec/workflow/states/pass_spec.rb
  spec/workflow/states/succeed_spec.rb
  spec/workflow/states/task_spec.rb
  spec/workflow/states/wait_spec.rb
  spec/workflow_spec.rb
Labels: refactoring

#211 Set StateHistory in Workflow not State
  lib/floe/workflow.rb
  lib/floe/workflow/state.rb
  spec/workflow/states/task_spec.rb
  spec/workflow/states/wait_spec.rb
Labels: refactoring

#190 Make Runner#wait optional
  lib/floe/runner.rb
  spec/runner_spec.rb
Labels: enhancement

#203 Pass credentials around with context
  exe/floe
  lib/floe/workflow.rb
  lib/floe/workflow/context.rb
  lib/floe/workflow/states/input_output_mixin.rb
  lib/floe/workflow/states/task.rb
  spec/spec_helper.rb
  spec/workflow/context_spec.rb
  spec/workflow/states/pass_spec.rb
  spec/workflow/states/task_spec.rb
  spec/workflow_spec.rb
Labels: refactoring

#208 Set `State["PreviousStateGuid"] in StateHistory
  lib/floe/workflow.rb
  lib/floe/workflow/state.rb
Labels: enhancement

#216 State without workflow
  lib/floe/workflow.rb
  lib/floe/workflow/context.rb
  lib/floe/workflow/state.rb
  lib/floe/workflow/states/choice.rb
  lib/floe/workflow/states/fail.rb
  lib/floe/workflow/states/input_output_mixin.rb
  lib/floe/workflow/states/non_terminal_mixin.rb
  lib/floe/workflow/states/pass.rb
  lib/floe/workflow/states/succeed.rb
  lib/floe/workflow/states/task.rb
  lib/floe/workflow/states/wait.rb
  spec/workflow/choice_rule_spec.rb
  spec/workflow/retrier_spec.rb
  spec/workflow/state_spec.rb
  spec/workflow/states/choice_spec.rb
  spec/workflow/states/fail_spec.rb
  spec/workflow/states/pass_spec.rb
  spec/workflow/states/succeed_spec.rb
  spec/workflow/states/task_spec.rb
  spec/workflow/states/wait_spec.rb
  spec/workflow_spec.rb
Labels: enhancement

#217 Add Apache-2.0 license
  LICENSE.txt
  README.md
  floe.gemspec
Labels: documentation

#224 Add a codeclimate config file
  .codeclimate.yml
Labels: test

#220 Move the guts of the CLI into a class for easier testing
  exe/floe
  lib/floe/cli.rb
  spec/cli_spec.rb
  spec/data/workflow.asl
  spec/exe/floe_spec.rb
Labels: performance

#226 Add an Execution unique ID to Context
  lib/floe/workflow.rb
Labels: enhancement

#214 Handle non-json input/output values
  lib/floe/workflow/context.rb
  lib/floe/workflow/state.rb
  spec/workflow/context_spec.rb
Labels: bug

#168 Set manageiq-style to at least 1.5.2
  .yamllint
  floe.gemspec
Labels: bug, dependencies

#225 Fix Input/Output handling for Pass, Choice, Succeed states
  lib/floe/workflow/path.rb
  lib/floe/workflow/states/choice.rb
  lib/floe/workflow/states/pass.rb
  lib/floe/workflow/states/succeed.rb
  spec/workflow/states/pass_spec.rb
  spec/workflow/states/succeed_spec.rb
Labels: bug

#186 Extract ErrorMatcherMixin from Catch and Retry
  lib/floe.rb
  lib/floe/workflow/catcher.rb
  lib/floe/workflow/error_matcher_mixin.rb
  lib/floe/workflow/retrier.rb
  lib/floe/workflow/states/task.rb
  spec/workflow/error_matcher_mixin_spec.rb
Labels: refactoring

#230 Output should be in json
  lib/floe/cli.rb
  lib/floe/workflow.rb
  lib/floe/workflow/context.rb
  lib/floe/workflow/state.rb
  lib/floe/workflow/states/task.rb
  spec/cli_spec.rb
  spec/workflow_spec.rb
Labels: enhancement
