Repository ManageIQ/floe, pull requests merged in 2024-05, with the labels that each got.

#180 drop unused Task#status
  lib/floe/workflow/states/task.rb
Labels: cleanup

#182 A failed state can leave a workflow in "running"
  CHANGELOG.md
  lib/floe/workflow/states/non_terminal_mixin.rb
  lib/floe/workflow/states/task.rb
  lib/floe/workflow/states/wait.rb
  spec/workflow/states/task_spec.rb
Labels: bug

#183 Check task failed? in non_terminal_mixin
  lib/floe/workflow/states/non_terminal_mixin.rb
  lib/floe/workflow/states/pass.rb
  lib/floe/workflow/states/task.rb
  lib/floe/workflow/states/wait.rb
Labels: bug

#188 Fix 2 basic Cops
  lib/floe/runner.rb
  lib/floe/workflow/states/succeed.rb
Labels: developer

#191 output now based upon raw input not effective input
  lib/floe/workflow/states/choice.rb
  lib/floe/workflow/states/pass.rb
  spec/workflow/states/pass_spec.rb
Labels: bug

#185 Minor changes to increase Coverage
  lib/floe/workflow/reference_path.rb
  lib/floe/workflow/states/task.rb
  spec/floe_spec.rb
  spec/runner_spec.rb
  spec/workflow/choice_rule_spec.rb
  spec/workflow/context_spec.rb
  spec/workflow/payload_template_spec.rb
  spec/workflow/state_spec.rb
  spec/workflow_spec.rb
Labels: developer

#192 require mfa
  floe.gemspec
Labels: security fix

#195 Fix error raised on invalid resource scheme
  lib/floe/workflow.rb
  spec/workflow_spec.rb
Labels: bug

#196 Cleanup payload tests for consistency
  spec/workflow_spec.rb
Labels: test

#201 fix initialize and rescue rubocop warnings
  lib/floe/runner.rb
  lib/floe/workflow.rb
Labels: technical debt
