Repository ManageIQ/floe, pull requests merged in 2024-08, with the labels that each got.

#253 Choice rule payload validation path
  lib/floe.rb
  lib/floe/workflow/choice_rule/data.rb
  lib/floe/workflow/path.rb
  lib/floe/workflow/state.rb
  spec/workflow/choice_rule_spec.rb
  spec/workflow/intrinsic_function_spec.rb
  spec/workflow/path_spec.rb
  spec/workflow/state_spec.rb
  spec/workflow/states/choice_spec.rb
  spec/workflow/states/pass_spec.rb
Labels: enhancement

#254 Split out ChoiceRule spec to be similar to other specs
  spec/workflow/choice_rule_spec.rb
  spec/workflow/states/choice_spec.rb
Labels: refactoring, test

#256 Intrinsics JsonToString and StringToJson
  lib/floe/workflow/intrinsic_function/parser.rb
  lib/floe/workflow/intrinsic_function/transformer.rb
  spec/workflow/intrinsic_function/parser_spec.rb
  spec/workflow/intrinsic_function_spec.rb
Labels: enhancement

#258 Add States.Format intrinsic function
  lib/floe/workflow/intrinsic_function/parser.rb
  lib/floe/workflow/intrinsic_function/transformer.rb
  spec/workflow/intrinsic_function/parser_spec.rb
  spec/workflow/intrinsic_function_spec.rb
Labels: enhancement

#255 Intrinsics States.JsonMerge
  lib/floe/workflow/intrinsic_function/parser.rb
  lib/floe/workflow/intrinsic_function/transformer.rb
  spec/workflow/intrinsic_function_spec.rb
Labels: enhancement

#259 Consistency cleanup
  lib/floe/workflow/intrinsic_function/transformer.rb
  spec/workflow/intrinsic_function/parser_spec.rb
  spec/workflow/intrinsic_function_spec.rb
Labels: cleanup

#260 Enable support for Hashes in States.Hash
  lib/floe/workflow/intrinsic_function/transformer.rb
  spec/workflow/intrinsic_function_spec.rb
Labels: enhancement

#261 Improve type check for States.Hash
  lib/floe/workflow/intrinsic_function/transformer.rb
  spec/workflow/intrinsic_function_spec.rb
Labels: enhancement

#264 Use Numeric over Integer || Float
  lib/floe/workflow/choice_rule/data.rb
  lib/floe/workflow/intrinsic_function/transformer.rb
  spec/workflow/intrinsic_function_spec.rb
Labels: cleanup

#257 In ChoiceRule::Data, parse compare key and variable
  lib/floe/workflow/choice_rule.rb
  lib/floe/workflow/choice_rule/data.rb
  spec/workflow/choice_rule_spec.rb
  spec/workflow/states/choice_spec.rb
Labels: enhancement

#265 Fix podman/docker container_ref trailing newline
  lib/floe/container_runner/docker.rb
  spec/container_runner/docker_spec.rb
  spec/container_runner/kubernetes_spec.rb
  spec/container_runner/podman_spec.rb
Labels: bug

#266 Implement "IsNumeric": false
  lib/floe/workflow/choice_rule/data.rb
  spec/workflow/choice_rule_spec.rb
Labels: enhancement

#268 Label containers/pods with workflow Execution ID
  lib/floe/container_runner/docker.rb
  lib/floe/container_runner/kubernetes.rb
  lib/floe/container_runner/podman.rb
  lib/floe/workflow.rb
  spec/container_runner/docker_spec.rb
  spec/container_runner/kubernetes_spec.rb
  spec/container_runner/podman_spec.rb
Labels: enhancement

#273 Choice: rename value to compare_predicate
  lib/floe/workflow/choice_rule/data.rb
Labels: enhancement

#274 More granular compare_key and determine path at initialization time
  lib/floe/workflow/choice_rule/data.rb
  spec/workflow/choice_rule_spec.rb
Labels: bug
